### ISSUE TITLE
Time Zone and Format change

### ISSUE THREAD

**Issue by GitCray** [martinbutt/openmiko#10]
WyzeCam v2. Release v1.0.0-alpha.2.  Downloaded and installed compiled bin from Releases, renamed to demo.bin
The time in the timestamp is GMT.
How one can change the time displayed in the correct timezone?
For example GMT+2
Also, is there a possibility to change the date\time format other than 12/24h?

**Comment by martinbutt** [comment]
The [base repo](https://github.com/openmiko/openmiko) has a wiki page describing [how to set a timezone](https://github.com/openmiko/openmiko/wiki/Setting-the-Time-Zone), and on [how to configure the video stream settings](https://github.com/openmiko/openmiko/wiki/Settings#settings). The [videocapture_settings.json](https://github.com/martinbutt/openmiko/blob/master/overlay_minimal/etc/videocapture_settings.json) file has more settings including `timestamp_24h`.

**Comment by GitCray** [comment]
Yes, thank you!
After many tries, and timezone codes, eventually I was able to log in via SSH and set it directly with commands

echo EST5EDT > /etc/TZ 
echo EST5EDT > /config/overlay/etc/TZ
