### ISSUE TITLE
wont join wifi:  Failed to add interface wlan0

### ISSUE THREAD

**Issue by EQNish** [martinbutt/openmiko#9]
Wyze Cam v2, upgraded from Release v0.0.40 to the v1.0.0-alpha.1.
copied my working (from .40) overlay with all of the conf files, added openmiko.conf
the openmiko.conf was edited to match initial settings, to include WIFI_MODULE=8189fs

[edit]  Forgot to add, I did not compile, I used the precompiled BIN renaming to demo.bin

This was the first cam to upgrade as a test before going full on install

nl80211: Failed to set interface 0 to mode 2: -19 (No such device)
wlan0: Failed to initialize driver interface
Failed to add interface wlan0
wlan0: Cancelling scan request
wlan0: Cancelling authentication timeout
wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/etc/wpa_supplicant.conf' driver 'nl80211' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/etc/wpa_supplicant.conf' -> '/etc/wpa_supplicant.conf'
Reading configuration file '/etc/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
bgscan='simple:30:-45:300'
Priority group 2
   id=0 ssid='XXXXXXX'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
Could not read interface wlan0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211: Remove monitor interface: refcount=0
netlink: Operstate: ifindex=0 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
Could not read interface wlan0 flags: No such device
nl80211: Set mode ifindex 0 iftype 2 (STATION)
nl80211: Failed to set interface 0 to mode 2: -19 (No such device)
wlan0: Failed to initialize driver interface
Failed to add interface wlan0
[wpa_supplicant.log](https://github.com/martinbutt/openmiko/files/10786415/wpa_supplicant.log)
[messages.log](https://github.com/martinbutt/openmiko/files/10786416/messages.log) had to add LOG to upload
[wpa_supplicant.conf.txt](https://github.com/martinbutt/openmiko/files/10786425/wpa_supplicant.conf.txt)  add .TXT to upload
[openmiko.conf.txt](https://github.com/martinbutt/openmiko/files/10786426/openmiko.conf.txt) add .TXT to upload

**Comment by martinbutt** [comment]
I tried your config files and the camera did not come online. After inspecting the only difference I found was DOS-style line endings in your config files. I converted them the UNIX-style line endings and it worked. I've added a fix to the [latest release](https://github.com/martinbutt/openmiko/releases/tag/v1.0.0-alpha.2) to handle the line endings. Can you try that and see if you have any luck?

**Comment by EQNish** [comment]
I see the Cam in my DHCP console, but no response from PING or HTTP requests.  I left it on throw the night to gather logs, attached!
[wpa_supplicant.log.1.gz](https://github.com/martinbutt/openmiko/files/10794763/wpa_supplicant.log.1.gz)
[wpa_supplicant.log.2.gz](https://github.com/martinbutt/openmiko/files/10794764/wpa_supplicant.log.2.gz)
[messages.1.gz](https://github.com/martinbutt/openmiko/files/10794765/messages.1.gz)
[messages.2.gz](https://github.com/martinbutt/openmiko/files/10794766/messages.2.gz)
[videocapture.log.1.gz](https://github.com/martinbutt/openmiko/files/10794767/videocapture.log.1.gz)
[videocapture.log.2.gz](https://github.com/martinbutt/openmiko/files/10794768/videocapture.log.2.gz)

**Comment by martinbutt** [comment]
From the log files, everything looks to be running. Could you zip up your entire `config/` directory for me to take a look at? I'm wondering if DOS-style line endings are preventing any other files from being read.

**Comment by EQNish** [comment]
I’ll get that too you this evening, I did redo the config files on my Linux machine, so they should have “clear” the extra DOS endings

**Comment by EQNish** [comment]
Got home tonight, checked the cam and it’s online, accessible…responding to ping and the web stream loads!  IDK< maybe it needed to bake, or just needed a few reboots?

The response time is still bad, getting an average of 1000ms, but I guess that’s better than before (average of 3k ms)

I’m gonna monitor for a few days and see how it goes before I move on to the other cams
